apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend-worker-annotation
  namespace: {{ .Release.Namespace }}
  labels:
    app: cvat-app
    tier: backend
    component: worker-annotation
    {{- include "cvat.labels" . | nindent 4 }}
    {{- with .Values.cvat.backend.worker.annotation.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.cvat.backend.worker.annotation.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.cvat.backend.worker.annotation.replicas }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "cvat.labels" . | nindent 6 }}
      {{- with .Values.cvat.backend.worker.annotation.labels }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      app: cvat-app
      tier: backend
      component: worker-annotation
  template:
    metadata:
      labels:
        app: cvat-app
        tier: backend
        component: worker-annotation
        {{- include "cvat.labels" . | nindent 8 }}
        {{- with .Values.cvat.backend.worker.annotation.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.cvat.backend.worker.annotation.annotations }}
      annotations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      containers:
        - name: cvat-app-backend-worker-annotation-container
          image: {{ .Values.cvat.backend.image }}:{{ .Values.cvat.backend.tag }}
          imagePullPolicy: {{ .Values.cvat.backend.imagePullPolicy }}
          {{- with .Values.cvat.backend.worker.annotation.resources }}
          resources:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          args: ["run", "worker.annotation"]
          env:
          {{ include "cvat.sharedBackendEnv" . | indent 10 }}
          {{- with .Values.cvat.backend.worker.annotation.additionalEnv }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          volumeMounts:
        {{- if not .Values.cvat.backend.disableDistinctCachePerService }}
          - mountPath: /home/django/data/cache
            name: cvat-worker-annotation-backend-cache
        {{- end }}
          - mountPath: /home/django/data
            name: cvat-backend-data
            subPath: data
          - mountPath: /home/django/keys
            name: cvat-backend-data
            subPath: keys
          - mountPath: /home/django/logs
            name: cvat-backend-data
            subPath: logs
          - mountPath: /home/django/models
            name: cvat-backend-data
            subPath: models
          - mountPath: /home/django/tmp_storage
            name: cvat-backend-data
            subPath: tmp_storage
          {{- with .Values.cvat.backend.worker.annotation.additionalVolumeMounts }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
      initContainers:
        {{- if .Values.cvat.backend.permissionFix.enabled }}
        - name: user-data-permission-fix
          image: busybox
          command: ["/bin/chmod", "-R", "777", "/home/django"]
          {{- with .Values.cvat.backend.worker.annotation.resources }}
          resources:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
          {{- if .Values.cvat.backend.defaultStorage.enabled }}
        {{- if not .Values.cvat.backend.disableDistinctCachePerService }}
          - mountPath: /home/django/data/cache
            name: cvat-worker-annotation-backend-cache
        {{- end }}
          - mountPath: /home/django/data
            name: cvat-backend-data
            subPath: data
          - mountPath: /home/django/keys
            name: cvat-backend-data
            subPath: keys
          - mountPath: /home/django/logs
            name: cvat-backend-data
            subPath: logs
          - mountPath: /home/django/models
            name: cvat-backend-data
            subPath: models
          {{- end }}
          {{- with .Values.cvat.backend.worker.annotation.additionalVolumeMounts }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
        {{- end }}
      {{- with .Values.cvat.backend.worker.annotation.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.cvat.backend.worker.annotation.tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{- if .Values.cvat.backend.defaultStorage.enabled }}
        - name: cvat-backend-data
          persistentVolumeClaim:
            claimName: "{{ .Release.Name }}-backend-data"
        - name: cvat-worker-annotation-backend-cache
          emptyDir: {}
        {{- end }}
        {{- with .Values.cvat.backend.worker.annotation.additionalVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
